cart/urls.py
from django.urls import path
from .views import cart_detail_view, cart_add_view, cart_remove_view

app_name = 'cart'

urlpatterns = [
    path('', cart_detail_view, name='cart_detail'),
    path('add/<int:product_id>/', cart_add_view, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove_view, name='cart_remove'),
]

shop/api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from shop.api import views


urlpatterns = [
    path('categories/', views.category_list),
    path('categories/<int:pk>/', views.category_detail),
    path('products/', views.product_list),
    path('products/<int:pk>/', views.product_detail),
]

urlpatterns = format_suffix_patterns(urlpatterns)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('home/', views.home_view, name='shop_home'),
    path('about/', views.about_view, name='shop_about'),
    path('', views.product_list_view, name='product_list'),
    path('<slug:category_slug>/', views.product_list_view, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail_view, name='product_detail'),
]

shop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),

    path('api/', include('shop.api.urls')),
]


# For Django to serve the uploaded media files using the development server.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    """docstring for Category
    Products are organized into different categories.
    """
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    # Retrieve the URL for a given object.
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    """docstring for Product
    The catalog of our shop will consist of products.
    """
    name = models.CharField(max_length=200, db_index=True)

    # The slug for this product to build beatiful URLs.
    slug = models.SlugField(max_length=200, db_index=True)

    image = models.ImageField(default='no_image.png',
                              upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,
                                decimal_places=2)
    stock = models.PositiveIntegerField(verbose_name='In stock')
    avaliable = models.BooleanField(default=True,
                                    verbose_name='Avaliable now')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # Many-to-one relationship.
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

    def __str__(self):
        return self.name

shop/api/views.py
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from shop.models import Category, Product
from shop.api.serializers import CategorySerializer, ProductSerializer


@api_view(['GET', 'POST'])
def category_list(request, format=None):
    """
    List all code categories, or create a new category.
    """
    if request.method == 'GET':
        categories = Category.objects.all()
        serializer = CategorySerializer(categories, many=True)
        return Response(serializer.data)

    elif request.method == 'POST':
        serializer = CategorySerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET', 'PUT', 'DELETE'])
def category_detail(request, pk, format=None):
    """
    Retrieve, update or delete a code category.
    """
    try:
        category = Category.objects.get(pk=pk)
    except Category.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = CategorySerializer(category)
        return Response(serializer.data)

    elif request.method == 'PUT':
        serializer = CategorySerializer(category, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == 'DELETE':
        category.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


@api_view(['GET', 'POST'])
def product_list(request, format=None):
    """
    List all code products, or create a new product.
    """
    if request.method == 'GET':
        products = Product.objects.all()
        serializer = ProductSerializer(products, many=True)
        return Response(serializer.data)

    elif request.method == 'POST':
        serializer = ProductSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET', 'PUT', 'DELETE'])
def product_detail(request, pk, format=None):
    """
    Retrieve, update or delete a code product.
    """
    try:
        product = Product.objects.get(pk=pk)
    except Product.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = ProductSerializer(product)
        return Response(serializer.data)

    elif request.method == 'PUT':
        serializer = ProductSerializer(product, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == 'DELETE':
        product.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product

from cart.forms import CartAddProductForm

# "category_slug" parameter to optionally filter products by a given category.


def product_list_view(request, category_slug=None):
    category = None
    categories = Category.objects.all()

    # Retrieve only avaliable products.
    products = Product.objects.filter(avaliable=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    context = {'category': category,
               'categories': categories,
               'products': products}
    return render(request, 'shop/product_list.html', context)


def product_detail_view(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, avaliable=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product_detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})


def home_view(request):
    return render(request, 'shop/home.html')


def about_view(request):
    return render(request, 'shop/about.html')

shop/templates/shop/about.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    About shop
{% endblock %}

{% block content %}
    <div class="container">
        <h3>About this shop</h3>
        <h1>Have a nice shopping!</h1>
    </div>
{% endblock %}

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'shop/base.css' %}">

    <title>{% block title %}Shop{% endblock %}</title>
    <link href="{% static "css/base.css" %} rel="stylesheet">
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Shop</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url "shop:shop_home" %}">Home</a>
              <a class="nav-item nav-link" href="{% url "shop:shop_about" %}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                  <a class="nav-item nav-link" href="{% url "cart:cart_detail" %}">
                    Your cart: {{ total_items }} item{{ total_items|pluralize }},
                    ${{ cart.get_total_price }}
                  </a>
                {% else %}
                  <a class="nav-item nav-link" href="{% url "cart:cart_detail" %}">
                    Your cart is still empty
                  </a>
                {% endif %}
              {% endwith %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

shop/templates/shop/home.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    Shop
{% endblock %}

{% block content %}
    <div class="container">
        <h3>Homepage Shop</h3>
        <strong>
            <h1>Welcome!</h1>
        </strong>
    </div>
{% endblock %}

shop/templates/shop/product_detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="product-detail">
            <div class="col-sm-8">
                <img src="{{ product.image.url }}" class="img-fluid" width="50%">
            </div>
            <h1>{{ product.name }}</h1>
            <h2>
                <a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a>
            </h2>
            <p class="price">${{ product.price }}</p>
            <form action="{% url "cart:cart_add" product.id %}" method="post">
                {{ cart_product_form }}
                {% csrf_token %}
                <input type="submit" value="Add to cart">
            </form>
            {{ product.description|linebreaks }}
        </div>
    </div>
{% endblock %}

shop/templates/shop/product_list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Products
    {% endif %}
{% endblock %}

{% block content %}
    <div id="sidebar">
        <h3>Categories</h3>
        <ul>
            <li {% if not category %} class="selected" {% endif %}>
                <a href="{% url "shop:product_list" %}">All</a>
            </li>
            {% for one_category in categories %}
                <li {% if category.slug == one_category.slug %} class="selected"
                {% endif %}>
                    <a href="{{ one_category.get_absolute_url }}">{{ one_category.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">
        <h1>{% if category %}
                {{ category.name }}
            {% else %}
                Products
            {% endif %}
        </h1>
        {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <div class="col-sm-8">
                        <img src="{{ product.image.url }}" alt="Default image" class="img-fluid"  width="100%">
                    </div>
                </a>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                <br>
                ${{ product.price }}
            </div>
        {% endfor %}
    </div>
{% endblock %}